### ISSUE TITLE
Add Netlify for PR deploy previews

### ISSUE THREAD

**Issue by hugovk** [helsinkijs/helsinkijs.org#11]
https://www.netlify.com is handy for generating deploy previews of sites. The free level is more than enough, and it can be helpful to avoid things like https://github.com/helsinkijs/helsinkijs.org/pull/8#issuecomment-491814768.

For example:

* https://github.com/citybikes/citybikes.github.io/pull/6 :arrow_right: https://deploy-preview-6--citybikes.netlify.com/

**Comment by eemeli** [comment]
This actually wouldn't have helped in this case, as the error was in not updating the GitHub config to match the move from serving from the repo root to `docs/`. The preview would've also looked fine in this case.

**Comment by eemeli** [comment]
Closing, as this isn't relevant for now. May reconsider later, of course.
